### PR TITLE
This is a PR just to show my class how CI works

### PR DESCRIPTION
**Pull request by agroce**

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
You might consider to switch to GH actions, they are quite a bit faster...

**Comment by agroce** [comment]
Yeah, colleagues at trail of bits already did on stuff I am involved in there, mostly.  I have been swamped (as always) so hadn't gotten around to looking into whether it's a big pain or really easy to translate my travis stuff over...

**Comment by agroce** [comment]
Looks like it's an hour-to-two hours effort to translate the .yml and then troubleshoot a bit to make sure it worked.  I think the frequency of changes right now to my main repos is low enough I'm going to postpone, but doesn't look too bad if research even pushes me into heavier commit cycles!  Thanks!

**Comment by mrbean-bremen** [comment]
Yeah, transferring it is quite straightforward, speeding it up may be a bit more work (like pinning package versions to get them cached between builds). I've done it a couple of times now (including with pyfakefs). Could be a student job :)

**Pull request closed without merging**
