### PR TITLE
 Renamed src path to tstl to conform to normal package behavior

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- package will be installed as "tstl" instead of "src" in site-packages

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
Ok, still something wrong here...

**Comment by agroce** [comment]
pyflakes is saying there's nothing in the tstl directory, and the install is failing.  Weird.

**Comment by mrbean-bremen** [comment]
Yeah, first time I did it right, but this time I accidentally moved src into tstl instead of renaming it, and didn't retest before pushing. Corrected now - hopefully the tests pass now.
Good that you have tests now :)

**Comment by agroce** [comment]
The tests didn't find any big smoking guns, but made bigger changes like this easier to make with some confidence, and found a lot of ugly corner cases in test reduction.

I'm running a new "exhaustive" (up to a depth) generator on pyfakefs right now, by the way, we'll see if it uncovers anything new.

**Comment by mrbean-bremen** [comment]
It will... I just had a run under Windows, and it found several errors (and than crashed - division by zero in `printStatus` because `thisElapsed` was 0). I was just thinking about making a PR for this, but you better know what to output in this case...

**Comment by agroce** [comment]
Hmm, I'll have to take a look at printStatus.  I'll hold off until the move to tstl works, though.

**Comment by mrbean-bremen** [comment]
Yes, any change would make a conflict with this one... Your tests take quite some time, though.

**Comment by agroce** [comment]
The tests are pretty thorough, since there's no good way to just do a shakedown of TSTL.  If something bad is broken, it fails fast, but if it's an ok build it takes a while.  Otherwise useless for things like a change to test reduction, though, that will only break one example or something.

**Comment by agroce** [comment]
(and I stupidly expected this wasn't working on the readme, so edited it, then created a conflict being "helpful" by doing the same change to randomtester directory you did, but a different way.

**Comment by mrbean-bremen** [comment]
Ok, the tests passed on [my branch](https://travis-ci.org/mrbean-bremen/tstl/builds/375596871) (without your merge commit), so it should be ok now.

**Comment by mrbean-bremen** [comment]
> I just had a run under Windows, and it found several errors 

Another followup - these have been mostly symlink-related, which works a bit shaky under Windows anyway and is rarely used (also you need admin rights to create a symlink).
I'm just running without symlink using the -M option, and this is also finding quite a lot - but most of this is related to `tell()` and look similar to the ones you already found. I may sort through them some time later to check if there is anything interesting.

**Comment by agroce** [comment]
The exhaustive run is still going (told you it was exhaustive), I'll triage the results when they come in for anything new and interesting.

**Pull request merged**
