### PR TITLE
Made print() functions from print stements for Python 3 compatibility

### PR DESCRIPTION
**Pull request by mrbean-bremen**

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
Made this new PR to start the modifications with the easy ones.

**Comment by agroce** [comment]
Any reason not to just merge this one, it seems pretty straightforward?  OTOH I don't have time to test it much until after some Dec 15 deadlines.

**Comment by agroce** [comment]
Oops, not the best idea:

SyntaxError: from __future__ imports must occur at the beginning of the file

ok, will fix real quick

**Comment by agroce** [comment]
Ok, this was maybe an incautious merge.  The issue is that yes, the prints in TSTL code are fixed.  The ones in the code TSTL generates are not.  The simple issue was not doing a "from __future__" in the sut.py, but the generated print statements also need to be fixed, which is going to need my knowledge of the generation.  But there may not be a lot of them.

**Comment by agroce** [comment]
Ok, I think that fixed the problems with generated code.

**Comment by agroce** [comment]
That will generally be the subtle thing here:  not only the TSTL code has to be 3.0+ compatible, but those changes have to reflect into the generated code as well.  I'll look for xranges in generated code.

**Comment by mrbean-bremen** [comment]
Sorry for that, it wasn't ready to merge. I was aware that there was generated code to be adapted, just didn't get to this yet (got distracted).

**Comment by agroce** [comment]
No problem, it was a very painless thing, since I just iterated running tstl_rt, fixing what it complained about on the import, and repeating until it worked.  Fortunately, almost all the auto-generated code gets generated every single time, so no issues there.

**Comment by agroce** [comment]
oops, missed one -- a feature only used in pyfakefs testing.  :)

fixed now, though

**Comment by mrbean-bremen** [comment]
Thanks, that was fast then! So, can you say what is missing for Python 3 support ? I actually haven't done anything serious yet...

**Comment by agroce** [comment]
It's possible this is it, but I bet there is something else I don't know about.

**Comment by mrbean-bremen** [comment]
I had another look, and there are at least a few issues with strings vs bytes (as to be expected). I will check if I can fix them later - my current approach is just run tstl with the pyfakefs example under Python 3, and then tstl_rt. I'm not sure how much of the actual functionality this covers - I guess I have to run more examples, and try different options., as there isn't a  test suite... I  may need your help with that later.

**Pull request merged**
